In [1]:
import os
import pandas as pd
import numpy as np

### Read financial time series simulations

In [2]:
source_code = os.path.join(os.getcwd())
data_files = os.path.join(source_code, "data")

dgp_simulations = os.listdir(os.path.join(data_files, "simulation"))

dgp_name = dgp_simulations[0]
dgp_name_summary = "_".join(dgp_name.split(".")[0].split("_")[:2])

In [3]:
rets_features = pd.read_csv(os.path.join(data_files, "simulation", dgp_simulations[0]), sep=",")
rets_features.columns = list(range(0, rets_features.shape[1]))

rets_features.tail()

0         1         2         3         4         5
1178  0.574134  1.185314 -2.135221  1.396963  1.465781  0.379528
1179 -0.346110  0.376818 -1.202009  0.286999 -0.301319 -0.656244
1180 -1.347234  1.170678 -0.849348 -1.447754  0.700321 -2.309333
1181  0.089634 -0.789695  1.136106 -1.240626  0.695460 -0.111975
1182 -0.452691  1.485636 -0.309389  1.293701  1.811287  0.118102

In [4]:
dgp = pd.read_csv(os.path.join(data_files, "DGP", "{}_B.csv".format(dgp_name_summary)), sep=",")
dgp.columns = list(range(dgp.shape[0], dgp.shape[1] + dgp.shape[0]))

dgp.tail()

6         7         8         9         10        11        12  \
1  0.015972  0.000000  0.075060  0.067476  0.000000 -0.074032  0.000000   
2  0.000000  0.000000  0.040917  0.030609  0.000000  0.000000  0.000000   
3  0.000000 -0.005070  0.016224  0.000000 -0.012265 -0.135449  0.004277   
4  0.000000 -0.004662  0.001755  0.000000  0.000000 -0.123139  0.000000   
5  0.000000  0.000000  0.025276  0.052771  0.000000 -0.085288  0.000000   

         13        14        15  ...  38        39        40        41  \
1  0.000000  0.000000  0.047014  ...   0  0.000000  0.000000  0.000000   
2  0.001067 -0.013911  0.000000  ...   0  0.000000 -0.006367 -0.004491   
3  0.008169  0.000000  0.000000  ...   0 -0.010694 -0.012266 -0.003466   
4  0.007864  0.000000  0.000000  ...   0  0.000000 -0.016150  0.000000   
5  0.000000  0.000000  0.018136  ...   0  0.000000 -0.013864 -0.012383   

         42       43  44  45        46        47  
1 -0.008524  0.01979   0   0  0.000000  0.034991  
2  0.000000  0.00000   0   0  0.000000  0.000000  
3  0.000000  0.00000   0   0  0.003868  0.010765  
4  0.000000  0.00000   0   0  0.000000  0.012223  
5  0.000000  0.00000   0   0  0.000000  0.027859  

[5 rows x 42 columns]

In [5]:
p = int((dgp.shape[1] / rets_features.shape[1]))
k = rets_features.shape[1]

In [6]:
count = k
for i in range(1, p + 1):
    for j in range(k):
        rets_features[count] = rets_features[j].shift(i)
        count += 1

In [7]:
rets_features = rets_features.dropna()

rets_features

0         1         2         3         4         5         6   \
7     1.993166 -0.849707 -0.333492  0.036613  0.280819 -0.819419  0.172910   
8    -0.384623  0.313387  0.422141 -0.449832 -0.048114 -0.179039  1.993166   
9     0.648169 -0.772028  1.652056  1.670741 -0.109904 -0.572845 -0.384623   
10   -1.372592  0.411914  0.981885  1.162538 -0.553074 -0.935610  0.648169   
11    1.036951 -0.241822 -1.031208 -1.508993  1.075138  0.517178 -1.372592   
...        ...       ...       ...       ...       ...       ...       ...   
1178  0.574134  1.185314 -2.135221  1.396963  1.465781  0.379528 -0.080417   
1179 -0.346110  0.376818 -1.202009  0.286999 -0.301319 -0.656244  0.574134   
1180 -1.347234  1.170678 -0.849348 -1.447754  0.700321 -2.309333 -0.346110   
1181  0.089634 -0.789695  1.136106 -1.240626  0.695460 -0.111975 -1.347234   
1182 -0.452691  1.485636 -0.309389  1.293701  1.811287  0.118102  0.089634   

            7         8         9   ...        38        39        40  \
7     2.730090  1.259242 -0.996195  ...  0.048810 -1.085705 -0.373970   
8    -0.849707 -0.333492  0.036613  ... -1.368697 -0.875759 -1.114491   
9     0.313387  0.422141 -0.449832  ...  0.491147 -0.114345  0.601553   
10   -0.772028  1.652056  1.670741  ...  0.827680  1.014956  1.381708   
11    0.411914  0.981885  1.162538  ... -0.107260  0.398302  0.470229   
...        ...       ...       ...  ...       ...       ...       ...   
1178  0.059763  1.436874 -0.751858  ...  0.200426 -0.301025  1.055802   
1179  1.185314 -2.135221  1.396963  ...  1.461771  0.733303  1.446477   
1180  0.376818 -1.202009  0.286999  ... -0.304604  0.664977 -0.753563   
1181  1.170678 -0.849348 -1.447754  ...  0.124232  2.253571 -0.881236   
1182 -0.789695  1.136106 -1.240626  ...  0.375778 -0.848451  0.858643   

            41        42        43        44        45        46        47  
7     0.938787  0.928701  0.694253 -2.646563  2.121203 -1.444718  1.143690  
8    -0.819987  1.060805  0.161501  0.048810 -1.085705 -0.373970  0.938787  
9     1.374663  0.849793 -1.979300 -1.368697 -0.875759 -1.114491 -0.819987  
10    1.509070  1.269280 -1.619266  0.491147 -0.114345  0.601553  1.374663  
11    0.766541 -0.259359  0.608076  0.827680  1.014956  1.381708  1.509070  
...        ...       ...       ...       ...       ...       ...       ...  
1178  0.694533  1.286434  0.089988 -0.900003  0.284846 -0.339015 -0.140583  
1179  1.326655 -0.187439  0.350321  0.200426 -0.301025  1.055802  0.694533  
1180 -0.893290 -0.737554 -0.829092  1.461771  0.733303  1.446477  1.326655  
1181 -1.007719 -0.230120 -0.379963 -0.304604  0.664977 -0.753563 -0.893290  
1182 -1.252129  0.649138 -0.002005  0.124232  2.253571 -0.881236 -1.007719  

[1176 rows x 48 columns]

In [8]:
dgp.shape

(6, 42)

In [9]:
rets_features.shape

(1176, 48)

### Example graph dataset

In [10]:
import torch
from torch_geometric.nn import GCNConv
from sklearn.metrics import roc_auc_score
from torch_geometric.utils import negative_sampling
from torch_geometric.data import InMemoryDataset, Data
import torch_geometric.transforms as T
from sklearn.model_selection import train_test_split

import networkx as nx

/Users/danieloliveira/opt/anaconda3/envs/torch/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [11]:
x = torch.tensor([[2,1], [5,6], [3,7], [12,0]], dtype=torch.float)
y = torch.tensor([0, 1, 0, 1], dtype=torch.float)

edge_index = torch.tensor([[0, 2, 1, 0, 3], [3, 1, 0, 1, 2]], dtype=torch.long)

data = Data(x=x, y=y, edge_index=edge_index)

In [12]:
x

tensor([[ 2.,  1.],
        [ 5.,  6.],
        [ 3.,  7.],
        [12.,  0.]])

In [13]:
edge_index

tensor([[0, 2, 1, 0, 3],
        [3, 1, 0, 1, 2]])

### Sketch of the graph dataset components

In [14]:
# create features
x = torch.from_numpy(rets_features.to_numpy()).type(torch.float32)

In [15]:
# create lables
y = None

In [16]:
edges = dgp.copy()

# create adjacency matrix
adj_matrix = np.where(edges.__abs__() != 0, 1, np.nan)
adj = pd.DataFrame(adj_matrix, index=edges.index, columns=edges.columns).reset_index().melt("index").dropna()

# create edge index
row = torch.from_numpy(adj.index.to_numpy().astype(np.int64)).to(torch.long)
col = torch.from_numpy(adj.variable.to_numpy().astype(np.int64)).to(torch.long)
edge_index = torch.stack([row, col], dim=0)

In [57]:
data = Data(x=x, y=y, edge_index=edge_index)

data

Data(x=[1176, 48], edge_index=[2, 80])

### Build GraphDataset class for time series simulations

In [58]:
class VGAE(torch.nn.Module):
    def __init__(self, n_input, n_hidden_units, n_output):
        super().__init__()
        self.conv1 = GCNConv(n_input, n_hidden_units)
        self.conv2 = GCNConv(n_hidden_units, n_output)

    def encode(self, x, edge_index):
        x = self.conv1(x, edge_index).relu()
        return self.conv2(x, edge_index)

    def decode(self, z, edge_label_index):
        return (z[edge_label_index[0]] * z[edge_label_index[1]]).sum(dim=-1)

    def decode_all(self, z):
        prob_adj = z @ z.t()
        return (prob_adj > 0).nonzero(as_tuple=False).t()

@torch.no_grad()
def eval_link_predictor(model, data):
    
    model.eval()
    z = model.encode(x=data.x, edge_index=data.edge_index)

    # sampling training negatives for every training epoch
    neg_edge_index = negative_sampling(edge_index=data.edge_index,
                                        num_nodes=data.num_nodes,
                                        num_neg_samples=data.edge_label_index.size(1), 
                                        method='sparse')

    edge_label_index = torch.cat(
        [data.edge_label_index, neg_edge_index],
        dim=-1,
    )
    edge_label = torch.cat([
        data.edge_label,
        data.edge_label.new_zeros(neg_edge_index.size(1))
    ], dim=0)

    out = model.decode(z=z, edge_label_index=edge_label_index).view(-1).sigmoid()

    return roc_auc_score(edge_label.cpu().numpy(), out.cpu().numpy())

# def train_link_predictor(model, train_data, val_data, optimizer, criterion, n_epochs=100):

#     for epoch in range(1, n_epochs + 1):

#         model.train()
#         optimizer.zero_grad()
#         z = model.encode(x=train_data.x, edge_index=train_data.edge_index)

#         # sampling training negatives for every training epoch
#         neg_edge_index = negative_sampling(edge_index=train_data.edge_index,
#                                            num_nodes=train_data.num_nodes,
#                                            num_neg_samples=train_data.edge_label_index.size(1), 
#                                            method='sparse')

#         edge_label_index = torch.cat(
#             [train_data.edge_label_index, neg_edge_index],
#             dim=-1,
#         )
#         edge_label = torch.cat([
#             train_data.edge_label,
#             train_data.edge_label.new_zeros(neg_edge_index.size(1))
#         ], dim=0)

#         out = model.decode(z, edge_label_index).view(-1)
#         loss = criterion(out, edge_label)
#         loss.backward()
#         optimizer.step()

#         val_auc = eval_link_predictor(model, val_data)

#         if epoch % 10 == 0:
#             print(f"Epoch: {epoch:03d}, Train Loss: {loss:.3f}, Val AUC: {val_auc:.3f}")

#     return model

In [59]:
split = T.RandomLinkSplit(
    num_val=0.1,
    num_test=0.1,
    is_undirected=True,
    add_negative_train_samples=False,
    neg_sampling_ratio=1.0,
)

train_data, val_data, test_data = split(data)

In [60]:
data.edge_index

tensor([[  0,   1,   6,   9,  10,  12,  13,  14,  15,  16,  17,  18,  19,  20,
          23,  27,  30,  31,  33,  34,  35,  39,  44,  45,  46,  50,  54,  55,
          59,  69,  72,  74,  75,  78,  79,  81,  82,  83,  86,  92,  93, 120,
         126, 138, 139, 150, 151, 152, 155, 158, 159, 160, 163, 165, 179, 180,
         183, 184, 185, 186, 187, 190, 201, 206, 207, 208, 209, 212, 213, 215,
         217, 222, 223, 240, 243, 246, 247, 249, 250, 251],
        [  6,   6,   7,   7,   7,   8,   8,   8,   8,   8,   8,   9,   9,   9,
           9,  10,  11,  11,  11,  11,  11,  12,  13,  13,  13,  14,  15,  15,
          15,  17,  18,  18,  18,  19,  19,  19,  19,  19,  20,  21,  21,  26,
          27,  29,  29,  31,  31,  31,  31,  32,  32,  32,  33,  33,  35,  36,
          36,  36,  36,  37,  37,  37,  39,  40,  40,  40,  40,  41,  41,  41,
          42,  43,  43,  46,  46,  47,  47,  47,  47,  47]])

In [62]:
train_data.edge_index

tensor([[1, 0, 6, 6, 6, 7],
        [6, 6, 7, 1, 0, 6]])

In [63]:
val_data.edge_index

tensor([[1, 0, 6, 6, 6, 7],
        [6, 6, 7, 1, 0, 6]])

In [64]:
test_data.edge_index

tensor([[1, 0, 6, 6, 6, 7],
        [6, 6, 7, 1, 0, 6]])

In [20]:
model = VGAE(n_input=x.shape[1],
             n_hidden_units=128,
             n_output=64).to("cpu")
optimizer = torch.optim.Adam(params=model.parameters(), lr=0.01)
criterion = torch.nn.BCEWithLogitsLoss()
n_epochs=100

In [21]:
epoch = 1

model.train()
optimizer.zero_grad()
z = model.encode(x=train_data.x, edge_index=train_data.edge_index)

In [22]:
# sampling training negatives for every training epoch
neg_edge_index = negative_sampling(edge_index=train_data.edge_index,
                                    num_nodes=train_data.num_nodes,
                                    num_neg_samples=train_data.edge_label_index.size(1), 
                                    method='sparse')

In [23]:
edge_label_index = torch.cat(
    [train_data.edge_label_index, neg_edge_index],
    dim=-1,
)
edge_label = torch.cat([
    train_data.edge_label,
    train_data.edge_label.new_zeros(neg_edge_index.size(1))
], dim=0)

In [24]:
out = model.decode(z, edge_label_index).view(-1)
loss = criterion(out, edge_label)
loss.backward()
optimizer.step()

In [27]:
model.eval()
z = model.encode(x=val_data.x, edge_index=val_data.edge_index)

# sampling training negatives for every training epoch
neg_edge_index = negative_sampling(edge_index=val_data.edge_index,
                                    num_nodes=val_data.num_nodes,
                                    num_neg_samples=val_data.edge_label_index.size(1), 
                                    method='sparse')

edge_label_index = torch.cat(
    [val_data.edge_label_index, neg_edge_index],
    dim=-1,
)
edge_label = torch.cat([
    val_data.edge_label,
    val_data.edge_label.new_zeros(neg_edge_index.size(1))
], dim=0)

In [31]:
val_data.edge_label_index.size(1)

0

In [28]:
out = model.decode(z=z, edge_label_index=edge_label_index).view(-1).sigmoid()

IndexError: tensors used as indices must be long, byte or bool tensors

In [22]:
for epoch in range(1, n_epochs + 1):

    model.train()
    optimizer.zero_grad()
    z = model.encode(x=train_data.x, edge_index=train_data.edge_index)

    # sampling training negatives for every training epoch
    neg_edge_index = negative_sampling(edge_index=train_data.edge_index,
                                        num_nodes=train_data.num_nodes,
                                        num_neg_samples=train_data.edge_label_index.size(1), 
                                        method='sparse')

    edge_label_index = torch.cat(
        [train_data.edge_label_index, neg_edge_index],
        dim=-1,
    )
    edge_label = torch.cat([
        train_data.edge_label,
        train_data.edge_label.new_zeros(neg_edge_index.size(1))
    ], dim=0)

    out = model.decode(z, edge_label_index).view(-1)
    loss = criterion(out, edge_label)
    loss.backward()
    optimizer.step()

    val_auc = eval_link_predictor(model, val_data)

    if epoch % 10 == 0:
        print(f"Epoch: {epoch:03d}, Train Loss: {loss:.3f}, Val AUC: {val_auc:.3f}")


ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

In [23]:
model

VGAE(
  (conv1): GCNConv(48, 128)
  (conv2): GCNConv(128, 64)
)

In [24]:
val_data

Data(x=[1176, 48], edge_index=[2, 6], edge_label=[0], edge_label_index=[2, 0])

In [26]:
model.eval()
z = model.encode(x=data.x, edge_index=data.edge_index)

In [29]:
data.edge_index

tensor([[  0,   1,   6,   9,  10,  12,  13,  14,  15,  16,  17,  18,  19,  20,
          23,  27,  30,  31,  33,  34,  35,  39,  44,  45,  46,  50,  54,  55,
          59,  69,  72,  74,  75,  78,  79,  81,  82,  83,  86,  92,  93, 120,
         126, 138, 139, 150, 151, 152, 155, 158, 159, 160, 163, 165, 179, 180,
         183, 184, 185, 186, 187, 190, 201, 206, 207, 208, 209, 212, 213, 215,
         217, 222, 223, 240, 243, 246, 247, 249, 250, 251],
        [  6,   6,   7,   7,   7,   8,   8,   8,   8,   8,   8,   9,   9,   9,
           9,  10,  11,  11,  11,  11,  11,  12,  13,  13,  13,  14,  15,  15,
          15,  17,  18,  18,  18,  19,  19,  19,  19,  19,  20,  21,  21,  26,
          27,  29,  29,  31,  31,  31,  31,  32,  32,  32,  33,  33,  35,  36,
          36,  36,  36,  37,  37,  37,  39,  40,  40,  40,  40,  41,  41,  41,
          42,  43,  43,  46,  46,  47,  47,  47,  47,  47]])

In [ ]:
out = model.decode(z=z, edge_label_index=data.edge_label_index).view(-1).sigmoid()

In [ ]:
# model = train_link_predictor(model=model,
#                              train_data=train_data,
#                              val_data=val_data,
#                              optimizer=optimizer,
#                              criterion=criterion)

test_auc = eval_link_predictor(model, test_data)
print(f"Test: {test_auc:.3f}")